### ISSUE TITLE
Great stuff!

### ISSUE THREAD

**Issue by berstend** [nswbmw/puppeteer-debug#1]
I really liked the idea so I made a [puppeteer-extra plugin](https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-repl) out of it, so I can use it with other puppeteer plugins. :)

I've added tab auto-completion for available properties, support for arbitrary objects (e.g. `browser`) and a colorized prompt.

I made sure to mention you in the credits, thanks! 👍

**Comment by nswbmw** [comment]
Thanks. I bump v2.0.0, use `vm.createContext()` instead of `eval()`, more flexible & keep context.
